
    // Auto-generated for VNet on 2023-07-05 10:35:43
    
    
    namespace VNet.Scientific.Measurement.Dimensions
    {
        public enum VolumeFlowUnit
        {
            AcreFootPerDay,
            AcreFootPerHour,
            AcreFootPerMinute,
            AcreFootPerSecond,
            CubicAttometerpersecond,
            CubicCentimeterPerMinute,
            CubicCentimeterpersecond,
            CubicDecimeterPerMinute,
            CubicDecimeterpersecond,
            CubicDekameterpersecond,
            CubicExameterpersecond,
            CubicFemtometerpersecond,
            CubicFootPerHour,
            CubicFootPerMinute,
            CubicFootPerSecond,
            CubicGigameterpersecond,
            CubicHectometerpersecond,
            CubicKilometerpersecond,
            CubicMegameterpersecond,
            CubicMeterPerDay,
            CubicMeterPerHour,
            CubicMeterPerMinute,
            CubicMeterPerSecond,
            CubicMicrometerpersecond,
            CubicMillimeterpersecond,
            CubicNanometerpersecond,
            CubicPetameterpersecond,
            CubicPicometerpersecond,
            CubicTerameterpersecond,
            CubicYardPerDay,
            CubicYardPerHour,
            CubicYardPerMinute,
            CubicYardPerSecond,
            CubicYoctometerpersecond,
            CubicYottameterpersecond,
            CubicZeptometerpersecond,
            CubicZettameterpersecond,
            KilousGallonPerMinute,
            LiterPerDay,
            LiterPerHour,
            LiterPerMinute,
            LiterPerSecond,
            MillionUsGallonPerDay,
            OilBarrelPerDay,
            OilBarrelPerHour,
            OilBarrelPerMinute,
            OilBarrelPerSecond,
            UkGallonPerDay,
            UkGallonPerHour,
            UkGallonPerMinute,
            UkGallonPerSecond,
            UsGallonPerDay,
            UsGallonPerHour,
            UsGallonPerMinute,
            UsGallonPerSecond,
        }
    }
