
    // Auto-generated for VNet on 2023-07-06 12:42:23
    
    
    namespace VNet.Scientific.Measurement.Dimensions
    {
        public enum VolumeUnit
        {
            AcreFoot,
            AuTablespoon,
            BoardFoot,
            CubicAttometer,
            CubicCentimeter,
            CubicDecimeter,
            CubicDekameter,
            CubicExameter,
            CubicFemtometer,
            CubicFoot,
            CubicGigameter,
            CubicHectometer,
            CubicInch,
            CubicKilometer,
            CubicMegameter,
            CubicMeter,
            CubicMicrometer,
            CubicMile,
            CubicMillimeter,
            CubicNanometer,
            CubicPetameter,
            CubicPicometer,
            CubicTerameter,
            CubicYard,
            CubicYoctometer,
            CubicYottameter,
            CubicZeptometer,
            CubicZettameter,
            ImperialBeerBarrel,
            ImperialGallon,
            ImperialOunce,
            ImperialPint,
            ImperialQuart,
            Liter,
            MetricCup,
            MetricTeaspoon,
            OilBarrel,
            UkTablespoon,
            UsBeerBarrel,
            UsCustomaryCup,
            UsGallon,
            UsLegalCup,
            UsOunce,
            UsPint,
            UsQuart,
            UsTablespoon,
            UsTeaspoon,
        }
    }
