// ReSharper disable UnusedMember.Global
// ReSharper disable SuggestBaseTypeForParameterInConstructor

namespace VNet.Scientific.Noise.Other;
// Salt and pepper noise, also known as impulse noise, is a type of noise that appears as random black and white pixels in an image or signal.
// It is typically caused by errors in transmission or data corruption. Salt and pepper noise can be generated by randomly replacing pixels with
// maximum or minimum intensity values.
public class SaltAndPepperNoise : NoiseBase
{
    public SaltAndPepperNoise(ISaltAndPepperNoiseAlgorithmArgs args)
        : base(args)
    {
    }

    public override double GenerateSingleSampleRaw()
    {
        var randomValue = GetRandomValue();
        if (randomValue < ((ISaltAndPepperNoiseAlgorithmArgs)Args).Density)
        {
            var saltOrPepper = GetRandomValue();
            return saltOrPepper < 0.5 ? ((ISaltAndPepperNoiseAlgorithmArgs)Args).SaltValue * Args.Scale : ((ISaltAndPepperNoiseAlgorithmArgs)Args).PepperValue * Args.Scale;
        }
        else
        {
            return Args.Scale * GetRandomValue();
        }
    }

    public override double[] GenerateRaw()
    {
        var totalSize = Args.Dimensions.Aggregate(1, (acc, val) => acc * val);
        var samples = new double[totalSize];

        for (var i = 0; i < totalSize; i++)
        {
            samples[i] = GenerateSingleSampleRaw();
        }

        return samples;
    }
}