
    // Auto-generated for VNet on 2023-12-14 12:00:46
    using System.Collections.Generic;
    
    
    namespace VNet.Scientific.Measurement
    {
        public static class DimensionDef
        {
            public static Dictionary<string, DimensionExponents> Exponents = new Dictionary<string, DimensionExponents>()
            {
            { "AbsorbedDoseOfIonizingRadiation", new DimensionExponents(2, 0, -2, 0, 0, 0, 0) },
            { "Acceleration", new DimensionExponents(1, 0, -2, 0, 0, 0, 0) },
            { "AmountOfSubstance", new DimensionExponents(0, 0, 0, 0, 0, 0, 1) },
            { "AmplitudeRatio", new DimensionExponents(0, 0, 0, 0, 0, 0, 0) },
            { "Angle", new DimensionExponents(0, 0, 0, 0, 0, 0, 0) },
            { "ApparentEnergy", new DimensionExponents(2, 1, -2, 0, 0, 0, 0) },
            { "ApparentPower", new DimensionExponents(2, 1, -3, 0, 0, 0, 0) },
            { "Area", new DimensionExponents(2, 0, 0, 0, 0, 0, 0) },
            { "AreaDensity", new DimensionExponents(-2, 1, 0, 0, 0, 0, 0) },
            { "AreaMomentOfInertia", new DimensionExponents(4, 0, 0, 0, 0, 0, 0) },
            { "BitRate", new DimensionExponents(0, 0, -1, 0, 0, 0, 0) },
            { "BrakeSpecificFuelConsumption", new DimensionExponents(-2, 0, 2, 0, 0, 0, 0) },
            { "Capacitance", new DimensionExponents(-2, -1, 4, 2, 0, 0, 0) },
            { "CoefficientOfThermalExpansion", new DimensionExponents(0, 0, 0, 0, 0, -1, 0) },
            { "Compressibility", new DimensionExponents(1, -1, 2, 0, 0, 0, 0) },
            { "Density", new DimensionExponents(-3, 1, 0, 0, 0, 0, 0) },
            { "Duration", new DimensionExponents(0, 0, 1, 0, 0, 0, 0) },
            { "DynamicViscosity", new DimensionExponents(-1, 1, -1, 0, 0, 0, 0) },
            { "ElectricAdmittance", new DimensionExponents(-2, -1, 3, 2, 0, 0, 0) },
            { "ElectricCharge", new DimensionExponents(0, 0, 1, 1, 0, 0, 0) },
            { "ElectricChargeDensity", new DimensionExponents(-3, 0, 1, 1, 0, 0, 0) },
            { "ElectricConductance", new DimensionExponents(-2, -1, 3, 2, 0, 0, 0) },
            { "ElectricConductivity", new DimensionExponents(-3, -1, 3, 2, 0, 0, 0) },
            { "ElectricCurrent", new DimensionExponents(0, 0, 0, 1, 0, 0, 0) },
            { "ElectricCurrentDensity", new DimensionExponents(-2, 0, 0, 1, 0, 0, 0) },
            { "ElectricCurrentGradient", new DimensionExponents(0, 0, -1, 1, 0, 0, 0) },
            { "ElectricField", new DimensionExponents(1, 1, -3, -1, 0, 0, 0) },
            { "ElectricInductance", new DimensionExponents(2, 1, -2, -2, 0, 0, 0) },
            { "ElectricPotential", new DimensionExponents(2, 1, -3, -1, 0, 0, 0) },
            { "ElectricPotentialAc", new DimensionExponents(0, 0, 0, 0, 0, 0, 0) },
            { "ElectricPotentialChangeRate", new DimensionExponents(2, 1, -4, -1, 0, 0, 0) },
            { "ElectricPotentialDc", new DimensionExponents(0, 0, 0, 0, 0, 0, 0) },
            { "ElectricResistance", new DimensionExponents(2, 1, -3, -2, 0, 0, 0) },
            { "ElectricResistivity", new DimensionExponents(3, 1, -3, -2, 0, 0, 0) },
            { "ElectricSurfaceChargeDensity", new DimensionExponents(-2, 0, 1, 1, 0, 0, 0) },
            { "Energy", new DimensionExponents(2, 1, -2, 0, 0, 0, 0) },
            { "EnergyDensity", new DimensionExponents(-1, 1, -2, 0, 0, 0, 0) },
            { "Entropy", new DimensionExponents(2, 1, -2, 0, 0, -1, 0) },
            { "Force", new DimensionExponents(1, 1, -2, 0, 0, 0, 0) },
            { "ForceChangeRate", new DimensionExponents(1, 1, -3, 0, 0, 0, 0) },
            { "ForcePerLength", new DimensionExponents(0, 1, -2, 0, 0, 0, 0) },
            { "Frequency", new DimensionExponents(0, 0, -1, 0, 0, 0, 0) },
            { "FuelEfficiency", new DimensionExponents(0, 0, 0, 0, 0, 0, 0) },
            { "HeatFlux", new DimensionExponents(0, 1, -3, 0, 0, 0, 0) },
            { "HeatTransferCoefficient", new DimensionExponents(0, 1, -3, 0, 0, -1, 0) },
            { "Illuminance", new DimensionExponents(-2, 0, 0, 0, 1, 0, 0) },
            { "Impulse", new DimensionExponents(1, 1, -1, 0, 0, 0, 0) },
            { "Information", new DimensionExponents(0, 0, 0, 0, 0, 0, 0) },
            { "InternationalUnit", new DimensionExponents(0, 0, 0, 0, 0, 0, 0) },
            { "Irradiance", new DimensionExponents(0, 1, -3, 0, 0, 0, 0) },
            { "Irradiation", new DimensionExponents(0, 1, -2, 0, 0, 0, 0) },
            { "Jerk", new DimensionExponents(1, 0, -3, 0, 0, 0, 0) },
            { "KinematicViscosity", new DimensionExponents(2, 0, -1, 0, 0, 0, 0) },
            { "LeakRate", new DimensionExponents(2, 1, -3, 0, 0, 0, 0) },
            { "Length", new DimensionExponents(1, 0, 0, 0, 0, 0, 0) },
            { "Level", new DimensionExponents(0, 0, 0, 0, 0, 0, 0) },
            { "LinearDensity", new DimensionExponents(-1, 1, 0, 0, 0, 0, 0) },
            { "LinearPowerDensity", new DimensionExponents(1, 1, -3, 0, 0, 0, 0) },
            { "Luminance", new DimensionExponents(-2, 0, 0, 0, 1, 0, 0) },
            { "Luminosity", new DimensionExponents(2, 1, -3, 0, 0, 0, 0) },
            { "LuminousFlux", new DimensionExponents(0, 0, 0, 0, 1, 0, 0) },
            { "LuminousIntensity", new DimensionExponents(0, 0, 0, 0, 1, 0, 0) },
            { "MagneticField", new DimensionExponents(0, 1, -2, -1, 0, 0, 0) },
            { "MagneticFlux", new DimensionExponents(2, 1, -2, -1, 0, 0, 0) },
            { "Magnetization", new DimensionExponents(-1, 0, 0, 1, 0, 0, 0) },
            { "Mass", new DimensionExponents(0, 1, 0, 0, 0, 0, 0) },
            { "MassConcentration", new DimensionExponents(-3, 1, 0, 0, 0, 0, 0) },
            { "MassFlow", new DimensionExponents(0, 1, -1, 0, 0, 0, 0) },
            { "MassFlux", new DimensionExponents(-2, 1, -1, 0, 0, 0, 0) },
            { "MassFraction", new DimensionExponents(0, 0, 0, 0, 0, 0, 0) },
            { "MassMomentOfInertia", new DimensionExponents(2, 1, 0, 0, 0, 0, 0) },
            { "MolarEnergy", new DimensionExponents(2, 1, -2, 0, 0, 0, -1) },
            { "MolarEntropy", new DimensionExponents(2, 1, -2, 0, 0, -1, -1) },
            { "MolarFlow", new DimensionExponents(0, 0, -1, 0, 0, 0, 1) },
            { "Molarity", new DimensionExponents(-3, 0, 0, 0, 0, 0, 1) },
            { "MolarMass", new DimensionExponents(0, 1, 0, 0, 0, 0, -1) },
            { "Permeability", new DimensionExponents(1, 1, -2, -2, 0, 0, 0) },
            { "Permittivity", new DimensionExponents(-3, -1, 4, 2, 0, 0, 0) },
            { "PorousMediumPermeability", new DimensionExponents(2, 0, 0, 0, 0, 0, 0) },
            { "Power", new DimensionExponents(2, 1, -3, 0, 0, 0, 0) },
            { "PowerDensity", new DimensionExponents(-1, 1, -3, 0, 0, 0, 0) },
            { "PowerRatio", new DimensionExponents(0, 0, 0, 0, 0, 0, 0) },
            { "Pressure", new DimensionExponents(-1, 1, -2, 0, 0, 0, 0) },
            { "PressureChangeRate", new DimensionExponents(-1, 1, -3, 0, 0, 0, 0) },
            { "Ratio", new DimensionExponents(0, 0, 0, 0, 0, 0, 0) },
            { "RatioChangeRate", new DimensionExponents(0, 0, -1, 0, 0, 0, 0) },
            { "ReactiveEnergy", new DimensionExponents(2, 1, -1, 0, 0, 0, 0) },
            { "ReactivePower", new DimensionExponents(2, 1, -3, 0, 0, 0, 0) },
            { "ReciprocalArea", new DimensionExponents(-2, 0, 0, 0, 0, 0, 0) },
            { "ReciprocalLength", new DimensionExponents(-1, 0, 0, 0, 0, 0, 0) },
            { "RelativeHumidity", new DimensionExponents(0, 0, 0, 0, 0, 0, 0) },
            { "RotationalAcceleration", new DimensionExponents(0, 0, -2, 0, 0, 0, 0) },
            { "RotationalSpeed", new DimensionExponents(0, 0, -1, 0, 0, 0, 0) },
            { "RotationalStiffness", new DimensionExponents(2, 1, -2, 0, 0, 0, 0) },
            { "RotationalStiffnessPerLength", new DimensionExponents(1, 1, -2, 0, 0, 0, 0) },
            { "Scalar", new DimensionExponents(0, 0, 0, 0, 0, 0, 0) },
            { "SolidAngle", new DimensionExponents(0, 0, 0, 0, 0, 0, 0) },
            { "SpecificEnergy", new DimensionExponents(2, 0, -2, 0, 0, 0, 0) },
            { "SpecificEntropy", new DimensionExponents(2, 0, -2, 0, 0, -1, 0) },
            { "SpecificFuelConsumption", new DimensionExponents(0, 0, 0, 0, 0, 0, 0) },
            { "SpecificVolume", new DimensionExponents(3, -1, 0, 0, 0, 0, 0) },
            { "SpecificWeight", new DimensionExponents(-2, 1, -2, 0, 0, 0, 0) },
            { "StandardVolumeFlow", new DimensionExponents(0, 1, -1, 0, 0, 0, 0) },
            { "Temperature", new DimensionExponents(0, 0, 0, 0, 0, 1, 0) },
            { "TemperatureChangeRate", new DimensionExponents(0, 0, -1, 0, 0, 1, 0) },
            { "TemperatureDelta", new DimensionExponents(0, 0, 0, 0, 0, 1, 0) },
            { "TemperatureGradient", new DimensionExponents(-1, 0, 0, 0, 0, 1, 0) },
            { "ThermalConductivity", new DimensionExponents(1, 1, -3, 0, 0, -1, 0) },
            { "ThermalResistance", new DimensionExponents(0, -1, 3, 0, 0, 1, 0) },
            { "Torque", new DimensionExponents(2, 1, -2, 0, 0, 0, 0) },
            { "TorquePerLength", new DimensionExponents(1, 1, -2, 0, 0, 0, 0) },
            { "Turbidity", new DimensionExponents(0, 0, 0, 0, 0, 0, 0) },
            { "Velocity", new DimensionExponents(1, 0, -1, 0, 0, 0, 0) },
            { "Volume", new DimensionExponents(3, 0, 0, 0, 0, 0, 0) },
            { "VolumeConcentration", new DimensionExponents(0, 0, 0, 0, 0, 0, 0) },
            { "VolumeFlow", new DimensionExponents(3, 0, -1, 0, 0, 0, 0) },
            { "VolumeFlowPerArea", new DimensionExponents(1, 0, -1, 0, 0, 0, 0) },
            { "VolumePerLength", new DimensionExponents(2, 0, 0, 0, 0, 0, 0) },
            { "VolumetricHeatCapacity", new DimensionExponents(-1, 1, -2, 0, 0, -1, 0) },
            { "WarpingMomentOfInertia", new DimensionExponents(6, 0, 0, 0, 0, 0, 0) },
            };
        }
    }
