namespace VNet.Scientific.Measurement;

public static partial class UnitDefinition
{
    public static readonly Dictionary<string, Dictionary<Enum, double>> ConversionFactors = new()
    {
        { "Length", new Dictionary<Enum, double>()
            {
                { LengthUnit.Angstrom, 1e-10 },
                { LengthUnit.AstronomicalUnit, 1.495978707e11 },
                { LengthUnit.Attometer, 1e-18 },
                { LengthUnit.Cana, 0.45 },
                { LengthUnit.Centimeter, 0.01 },
                { LengthUnit.Chain, 20.1168 },
                { LengthUnit.Chi, 0.333 },
                { LengthUnit.Cubit, 0.5 },
                { LengthUnit.Decameter, 10 },
                { LengthUnit.Decimeter, 0.1 },
                { LengthUnit.Femtometer, 1e-15 },
                { LengthUnit.Fathom, 1.8288 },
                { LengthUnit.Foot, 0.3048 },
                { LengthUnit.Furlong, 201.168 },
                { LengthUnit.Gigameter, 1e7 },
                { LengthUnit.Hectometer, 100 },
                { LengthUnit.HubbleLength, 4.4e26 },
                { LengthUnit.Inch, 0.0254 },
                { LengthUnit.Kilometer, 1000 },
                { LengthUnit.League, 4828.032 },
                { LengthUnit.Li, 500 },
                { LengthUnit.LightYear, 9.461e15 },
                { LengthUnit.Megameter, 1e6 },
                { LengthUnit.Meter, 1 },
                { LengthUnit.Micrometer, 1e-6 },
                { LengthUnit.Micron, 1e-6 },
                { LengthUnit.Mile, 1609.344 },
                { LengthUnit.Millimeter, 0.001 },
                { LengthUnit.Nanometer, 1e-9 },
                { LengthUnit.NauticalMile, 1852 },
                { LengthUnit.Pace, 0.762 },
                { LengthUnit.Parsec, 3.086e16 },
                { LengthUnit.Picometer, 1e-12 },
                { LengthUnit.PlanckLength, 1.616255e-35 },
                { LengthUnit.Rod, 5.0292 },
                { LengthUnit.Rope, 6.096 },
                { LengthUnit.Terameter, 1e8 },
                { LengthUnit.Thou, 2.54e-5 },
                { LengthUnit.Verst, 1066.8 },
                { LengthUnit.Yard, 0.9144 }
            }
        },
//        {
//            "Mass", new Dictionary<Enum, double>()
//            {
//                { MassUnit.AtomicMassUnit, 1.66053906660e-24 },
//                { MassUnit.Carat, 0.2 },
//                { MassUnit.Centigram, 0.01 },
//                { MassUnit.Decagram, 10 },
//                { MassUnit.Decigram, 0.1 },
//                { MassUnit.ElectronVolt, 1.78266192e-36 },
//                { MassUnit.Exagram, 1e18 },
//                { MassUnit.Femtogram, 1e-15 },
//                { MassUnit.Gigagram, 1e9 },
//                { MassUnit.Gram, 1 },
//                { MassUnit.Grave, 1.42857142857 },
//                { MassUnit.Hectogram, 100 },
//                { MassUnit.Jin, 500 },
//                { MassUnit.Jupiter, 1.8982e27 },
//                { MassUnit.Kilogram, 1000 },
//                { MassUnit.Liang, 50 },
//                { MassUnit.Li, 500 },
//                { MassUnit.LongTon, 1016046.9088 },
//                { MassUnit.Mace, 0.00375 },
//                { MassUnit.Megagram, 1e6 },
//                { MassUnit.Microgram, 1e-6 },
//                { MassUnit.Milligram, 0.001 },
//                { MassUnit.Nanogram, 1e-9 },
//                { MassUnit.Ounce, 28.349523125 },
//                { MassUnit.Pennyweight, 1.55517384 },
//                { MassUnit.Picogram, 1e-12 },
//                { MassUnit.PlanckMass, 2.176434e-8 },
//                { MassUnit.Pound, 453.59237 },
//                { MassUnit.ShortTon, 907184.74 },
//                { MassUnit.SolarMass, 1.98847e30 },
//                { MassUnit.Stone, 6350.29318 },
//                { MassUnit.Tael, 37.5 },
//                { MassUnit.Teragram, 1e12 },
//                { MassUnit.Tonne, 1000000 },
//                { MassUnit.Ton, 907184.74 },
//                { MassUnit.TroyOunce, 31.1034768 },
//                { MassUnit.TroyPound, 373.2417216 },
//                { MassUnit.UKHundredweight, 50802.34544 },
//                { MassUnit.USHundredweight, 45359.237 },
//                { MassUnit.Cash, 0.001 },
//                { MassUnit.Candareen, 0.00133 },
//                { MassUnit.Catty, 604.789 },
//                { MassUnit.Fen, 0.003 },
//                { MassUnit.Hao, 0.005 },
//                { MassUnit.Qian, 0.01 },
//                { MassUnit.Dan, 50 },
//                { MassUnit.Piculi, 0.604789 }
//            }
//        },
//        {
//            "Time", new Dictionary<Enum, double>()
//            {
//                { TimeUnit.PlanckTime, 5.39106e-44 },
//                { TimeUnit.Yoctosecond, 1e-24 },
//                { TimeUnit.Zeptosecond, 1e-21 },
//                { TimeUnit.Attosecond, 1e-18 },
//                { TimeUnit.Femtosecond, 1e-15 },
//                { TimeUnit.Picosecond, 1e-12 },
//                { TimeUnit.Nanosecond, 1e-9 },
//                { TimeUnit.Microsecond, 1e-6 },
//                { TimeUnit.Millisecond, 0.001 },
//                { TimeUnit.Second, 1 },
//                { TimeUnit.Third, 1.33333333333 },
//                { TimeUnit.Fourth, 0.75 },
//                { TimeUnit.Minute, 60 },
//                { TimeUnit.Hour, 3600 },
//                { TimeUnit.Day, 86400 },
//                { TimeUnit.Week, 604800 },
//                { TimeUnit.Fortnight, 1209600 },
//                { TimeUnit.Month, 2629800 },
//                { TimeUnit.Year, 31557600 },
//                { TimeUnit.Decade, 315576000 },
//                { TimeUnit.Century, 3155760000 },
//                { TimeUnit.Millennium, 31557600000 },
//                { TimeUnit.GalacticYear, 2.62974e17 },
//                { TimeUnit.MartianDay, 88642.663 },
//                { TimeUnit.LunarDay, 86164.0916 },
//                { TimeUnit.SolarDay, 86400 },
//                { TimeUnit.SiderealYear, 31558149.7635 },
//                { TimeUnit.Microfortnight, 0.0864 },
//                { TimeUnit.Jiffy, 0.01 },
//                { TimeUnit.Shake, 1e-8 },
//                { TimeUnit.LightMile, 5.368414e-12 },
//                { TimeUnit.LightFoot, 1.097373e-11 },
//                { TimeUnit.LightMeter, 3.335641e-9 },
//                { TimeUnit.LightKilometer, 1.079252e-9 },
//                { TimeUnit.Miao, 0.0666666667 },
//                { TimeUnit.Fen, 0.006 },
//                { TimeUnit.Ke, 0.0001 },
//                { TimeUnit.Dian, 0.024 },
//                { TimeUnit.Shi, 0.24 },
//                { TimeUnit.Shichen, 1 },
//                { TimeUnit.Xiaoshi, 2 },
//                { TimeUnit.Ri, 86400 },
//                { TimeUnit.Tian, 86400 }
//            }
//        },
//        {
//            "ElectricalCurrent", new Dictionary<Enum, double>()
//            {
//                { ElectricalCurrentUnit.Ampere, 1 },
//                { ElectricalCurrentUnit.Abampere, 10 },
//                { ElectricalCurrentUnit.Biot, 10 },
//                { ElectricalCurrentUnit.Milliampere, 0.001 },
//                { ElectricalCurrentUnit.Microampere, 0.000001 },
//                { ElectricalCurrentUnit.Nanoampere, 0.000000001 },
//                { ElectricalCurrentUnit.Picoampere, 0.000000000001 },
//                { ElectricalCurrentUnit.Femtoampere, 0.000000000000001 },
//                { ElectricalCurrentUnit.Attoampere, 0.000000000000000001 },
//                { ElectricalCurrentUnit.Kiloampere, 1000 },
//                { ElectricalCurrentUnit.Megaampere, 1000000 },
//                { ElectricalCurrentUnit.Gigaampere, 1000000000 },
//                { ElectricalCurrentUnit.Teraampere, 1000000000000 },
//                { ElectricalCurrentUnit.Petaampere, 1000000000000000 },
//                { ElectricalCurrentUnit.Exaampere, 1000000000000000000 },
//                { ElectricalCurrentUnit.Zettaampere, 1e21 },
//                { ElectricalCurrentUnit.Yottaampere, 1e24 },
//                { ElectricalCurrentUnit.Rayleigh, 1.11111111111e-18 },
//                { ElectricalCurrentUnit.Abiampere, 10 },
//                { ElectricalCurrentUnit.Statampere, 3.335641e-10 },
//                { ElectricalCurrentUnit.ESUperSecond, 3.335641e-10 },
//                { ElectricalCurrentUnit.CoulombPerSecond, 1 },
//                { ElectricalCurrentUnit.Gilbert, 0.79577472 },
//                { ElectricalCurrentUnit.EMUperSecond, 0.79577472 }
//            }
//            },
//            {"LuminousIntensity", new Dictionary<Enum, double>()
//            {
//                { LuminousIntensityUnit.Candela, 1 },
//                { LuminousIntensityUnit.Candle, 1 },
//                { LuminousIntensityUnit.Candlepower, 1 },
//                { LuminousIntensityUnit.Carcel, 9.81 },
//                { LuminousIntensityUnit.Hefnerkerze, 0.92 },
//                { LuminousIntensityUnit.CandelaPerSquareMeter, 1 },
//                { LuminousIntensityUnit.Kilocandela, 1000 },
//                { LuminousIntensityUnit.Megacandela, 1000000 },
//                { LuminousIntensityUnit.Millicandela, 0.001 },
//                { LuminousIntensityUnit.Nit, 1 },
//                { LuminousIntensityUnit.Stilb, 10000 },
//                { LuminousIntensityUnit.Lambert, 3183.09886184 },
//                { LuminousIntensityUnit.FootLambert, 10.76391 }
//            }
//                },
//            {
//            "Temperature", new Dictionary<Enum, double>()
//            {
//                { TemperatureUnit.Kelvin, 1 },
//                { TemperatureUnit.Celsius, 274.15 },
//                { TemperatureUnit.Fahrenheit, 255.37222222222 },
//                { TemperatureUnit.Rankine, 1.8 },
//                { TemperatureUnit.Delisle, 551.67 },
//                { TemperatureUnit.Newton, 33 },
//                { TemperatureUnit.Reaumur, 218.52 },
//                { TemperatureUnit.Romer, 260.26 },
//                { TemperatureUnit.GasMark, 457.87 }
//            }
//            },
//            {
//            "Amount", new Dictionary<Enum, double>()
//            {
//                { AmountUnit.Unit, 1 },
//                { AmountUnit.Dozen, 12 },
//                { AmountUnit.Score, 20 },
//                { AmountUnit.Gross, 144 },
//                { AmountUnit.Mole, 6.02214076e23 },
//                { AmountUnit.Pair, 2 },
//                { AmountUnit.Ream, 500 },
//                { AmountUnit.Couple, 2 },
//                { AmountUnit.Peck, 2 },
//                { AmountUnit.Case, 24 },
//                { AmountUnit.GrossScore, 1728 },
//                { AmountUnit.Quire, 25 },
//                { AmountUnit.Sheet, 1 },
//                { AmountUnit.BakerDozen, 13 },
//                { AmountUnit.Cartons, 12 },
//                { AmountUnit.Fortnight, 14 },
//                { AmountUnit.Bale, 5 },
//                { AmountUnit.MetricTon, 1000 },
//                { AmountUnit.Hundredweight, 100 },
//                { AmountUnit.Bushel, 35.2391 },
//                { AmountUnit.Octad, 8 },
//                { AmountUnit.GrossHundredweight, 14400 }
//            }
//        }
    };
}