//namespace VNet.Scientific.Measurement;

//public static partial class UnitDefinition
//{
//    public static readonly Dictionary<string, Dictionary<Enum, string>> Symbols = new()
//    {
//        { "Length", new Dictionary<Enum, string>()
//            {
//                { LengthUnit.Angstrom, "Å" },
//                { LengthUnit.AstronomicalUnit, "au" },
//                { LengthUnit.Attometer, "am" },
//                { LengthUnit.Cana, "cana" },
//                { LengthUnit.Centimeter, "cm" },
//                { LengthUnit.Chain, "ch" },
//                { LengthUnit.Chi, "尺" },
//                { LengthUnit.Cubit, "cubit" },
//                { LengthUnit.Decameter, "dam" },
//                { LengthUnit.Decimeter, "dm" },
//                { LengthUnit.Femtometer, "fm" },
//                { LengthUnit.Fathom, "ftm" },
//                { LengthUnit.Foot, "ft" },
//                { LengthUnit.Furlong, "fur" },
//                { LengthUnit.Hectometer, "hm" },
//                { LengthUnit.HubbleLength, "Hubble length" },
//                { LengthUnit.Inch, "in" },
//                { LengthUnit.Kilometer, "km" },
//                { LengthUnit.League, "lea" },
//                { LengthUnit.Li, "里" },
//                { LengthUnit.LightYear, "ly" },
//                { LengthUnit.Megameter, "Mm" },
//                { LengthUnit.Meter, "m" },
//                { LengthUnit.Micrometer, "µm" },
//                { LengthUnit.Micron, "µ" },
//                { LengthUnit.Mile, "mi" },
//                { LengthUnit.Millimeter, "mm" },
//                { LengthUnit.Nanometer, "nm" },
//                { LengthUnit.NauticalMile, "nmi" },
//                { LengthUnit.Pace, "pace" },
//                { LengthUnit.Parsec, "pc" },
//                { LengthUnit.Picometer, "pm" },
//                { LengthUnit.PlanckLength, "Planck" },
//                { LengthUnit.Rod, "rd" },
//                { LengthUnit.Rope, "rope" },
//                { LengthUnit.Thou, "th" },
//                { LengthUnit.Verst, "Verst" },
//                { LengthUnit.Yard, "yd" }
//            }
//        },
//        {
//            "Mass", new Dictionary<Enum, string>()
//            {
//                { MassUnit.AtomicMassUnit, "u" },
//                { MassUnit.Carat, "ct" },
//                { MassUnit.Centigram, "cg" },
//                { MassUnit.Decagram, "dag" },
//                { MassUnit.Decigram, "dg" },
//                { MassUnit.ElectronVolt, "eV" },
//                { MassUnit.Exagram, "Eg" },
//                { MassUnit.Femtogram, "fg" },
//                { MassUnit.Gigagram, "Gg" },
//                { MassUnit.Gram, "g" },
//                { MassUnit.Hectogram, "hg" },
//                { MassUnit.Jin, "斤" },
//                { MassUnit.Jupiter, "Mᴊ" },
//                { MassUnit.Kilogram, "kg" },
//                { MassUnit.Liang, "两" },
//                { MassUnit.Li, "斤" },
//                { MassUnit.LongTon, "LT" },
//                { MassUnit.Mace, "钱" },
//                { MassUnit.Megagram, "Mg" },
//                { MassUnit.Microgram, "µg" },
//                { MassUnit.Milligram, "mg" },
//                { MassUnit.Nanogram, "ng" },
//                { MassUnit.Ounce, "oz" },
//                { MassUnit.Pennyweight, "dwt" },
//                { MassUnit.Picogram, "pg" },
//                { MassUnit.PlanckMass, "mₚ" },
//                { MassUnit.Pound, "lb" },
//                { MassUnit.ShortTon, "ST" },
//                { MassUnit.SolarMass, "M☉" },
//                { MassUnit.Stone, "st" },
//                { MassUnit.Tael, "两" },
//                { MassUnit.Teragram, "Tg" },
//                { MassUnit.Tonne, "t" },
//                { MassUnit.TroyOunce, "oz t" },
//                { MassUnit.TroyPound, "lb t" },
//                { MassUnit.UKHundredweight, "cwt" },
//                { MassUnit.USHundredweight, "cwt" },
//                { MassUnit.Cash, "文" },
//                { MassUnit.Candareen, "分" },
//                { MassUnit.Catty, "斤" },
//                { MassUnit.Fen, "分" },
//                { MassUnit.Hao, "毫" },
//                { MassUnit.Qian, "钱" },
//                { MassUnit.Dan, "担" },
//                { MassUnit.Piculi, "市斤" }
//            }
//        },
//        {
//            "Time", new Dictionary<Enum, string>()
//            {
//                { TimeUnit.PlanckTime, "tₚ" },
//                { TimeUnit.Yoctosecond, "ys" },
//                { TimeUnit.Zeptosecond, "zs" },
//                { TimeUnit.Attosecond, "as" },
//                { TimeUnit.Femtosecond, "fs" },
//                { TimeUnit.Picosecond, "ps" },
//                { TimeUnit.Nanosecond, "ns" },
//                { TimeUnit.Microsecond, "µs" },
//                { TimeUnit.Millisecond, "ms" },
//                { TimeUnit.Second, "s" },
//                { TimeUnit.Third, "rd" },
//                { TimeUnit.Fourth, "th" },
//                { TimeUnit.Minute, "min" },
//                { TimeUnit.Hour, "hr" },
//                { TimeUnit.Day, "day" },
//                { TimeUnit.Week, "wk" },
//                { TimeUnit.Fortnight, "fortnight" },
//                { TimeUnit.Month, "month" },
//                { TimeUnit.Year, "yr" },
//                { TimeUnit.Decade, "decade" },
//                { TimeUnit.Century, "century" },
//                { TimeUnit.Millennium, "millennium" },
//                { TimeUnit.NanosecondSidereal, "ns (sidereal)" },
//                { TimeUnit.MicrosecondSidereal, "µs (sidereal)" },
//                { TimeUnit.MillisecondSidereal, "ms (sidereal)" },
//                { TimeUnit.SecondSidereal, "s (sidereal)" },
//                { TimeUnit.MinuteSidereal, "min (sidereal)" },
//                { TimeUnit.HourSidereal, "hr (sidereal)" },
//                { TimeUnit.DaySidereal, "day (sidereal)" },
//                { TimeUnit.WeekSidereal, "wk (sidereal)" },
//                { TimeUnit.MonthSidereal, "month (sidereal)" },
//                { TimeUnit.YearSidereal, "yr (sidereal)" },
//                { TimeUnit.MartianDay, "sol" },
//                { TimeUnit.LunarDay, "Lunar day" },
//                { TimeUnit.SolarDay, "Solar day" },
//                { TimeUnit.SiderealYear, "Sidereal year" },
//                { TimeUnit.Microfortnight, "µfn" },
//                { TimeUnit.Jiffy, "jiffy" },
//                { TimeUnit.Shake, "shake" },
//                { TimeUnit.LightMile, "light-mile" },
//                { TimeUnit.LightFoot, "light-ft" },
//                { TimeUnit.LightMeter, "light-m" },
//                { TimeUnit.LightKilometer, "light-km" },
//                { TimeUnit.Miao, "秒" },
//                { TimeUnit.Fen, "分" },
//                { TimeUnit.Ke, "刻" },
//                { TimeUnit.Dian, "点" },
//                { TimeUnit.Shi, "时" },
//                { TimeUnit.Shichen, "时辰" },
//                { TimeUnit.Xiaoshi, "小时" },
//                { TimeUnit.Ri, "日" },
//                { TimeUnit.Tian, "天" }
//            }
//        },
//        {
//            "ElectricalCurrent", new Dictionary<Enum, string>()
//            {
//                { ElectricalCurrentUnit.Ampere, "A" },
//                { ElectricalCurrentUnit.Abampere, "abA" },
//                { ElectricalCurrentUnit.Biot, "Bi" },
//                { ElectricalCurrentUnit.Milliampere, "mA" },
//                { ElectricalCurrentUnit.Microampere, "µA" },
//                { ElectricalCurrentUnit.Nanoampere, "nA" },
//                { ElectricalCurrentUnit.Picoampere, "pA" },
//                { ElectricalCurrentUnit.Femtoampere, "fA" },
//                { ElectricalCurrentUnit.Attoampere, "aA" },
//                { ElectricalCurrentUnit.Kiloampere, "kA" },
//                { ElectricalCurrentUnit.Megaampere, "MA" },
//                { ElectricalCurrentUnit.Gigaampere, "GA" },
//                { ElectricalCurrentUnit.Teraampere, "TA" },
//                { ElectricalCurrentUnit.Petaampere, "PA" },
//                { ElectricalCurrentUnit.Exaampere, "EA" },
//                { ElectricalCurrentUnit.Zettaampere, "ZA" },
//                { ElectricalCurrentUnit.Yottaampere, "YA" },
//                { ElectricalCurrentUnit.Rayleigh, "Ry" },
//                { ElectricalCurrentUnit.Abiampere, "aA" },
//                { ElectricalCurrentUnit.Statampere, "statA" },
//                { ElectricalCurrentUnit.ESUperSecond, "ESU/s" },
//                { ElectricalCurrentUnit.CoulombPerSecond, "C/s" },
//                { ElectricalCurrentUnit.Gilbert, "Gi" },
//                { ElectricalCurrentUnit.EMUperSecond, "EMU/s" }
//            }
//        },
//        {
//            "LuminousIntensity", new Dictionary<Enum, string>()
//            {
//                { LuminousIntensityUnit.Candela, "cd" },
//                { LuminousIntensityUnit.Candle, "cd" },
//                { LuminousIntensityUnit.Candlepower, "cd" },
//                { LuminousIntensityUnit.Carcel, "car" },
//                { LuminousIntensityUnit.Hefnerkerze, "HefnK" },
//                { LuminousIntensityUnit.CandelaPerSquareMeter, "cd/m²" },
//                { LuminousIntensityUnit.Kilocandela, "kcd" },
//                { LuminousIntensityUnit.Megacandela, "Mcd" },
//                { LuminousIntensityUnit.Millicandela, "mcd" },
//                { LuminousIntensityUnit.Nit, "nt" },
//                { LuminousIntensityUnit.Stilb, "sb" },
//                { LuminousIntensityUnit.Lambert, "L" },
//                { LuminousIntensityUnit.FootLambert, "fL" }
//            }
//        },
//        {
//            "Temperature", new Dictionary<Enum, string>()
//            {
//                { TemperatureUnit.Kelvin, "K" },
//                { TemperatureUnit.Celsius, "°C" },
//                { TemperatureUnit.Fahrenheit, "°F" },
//                { TemperatureUnit.Rankine, "°R" },
//                { TemperatureUnit.Delisle, "°De" },
//                { TemperatureUnit.Newton, "°N" },
//                { TemperatureUnit.Reaumur, "°Ré" },
//                { TemperatureUnit.Romer, "°Rø" },
//                { TemperatureUnit.GasMark, "GM" }
//            }
//        },
//        {
//            "Amount", new Dictionary<Enum, string>()
//            {
//                { AmountUnit.Unit, "u" },
//                { AmountUnit.Dozen, "doz" },
//                { AmountUnit.Score, "score" },
//                { AmountUnit.Gross, "gr" },
//                { AmountUnit.Mole, "mol" },
//                { AmountUnit.Pair, "pair" },
//                { AmountUnit.Ream, "ream" },
//                { AmountUnit.Couple, "couple" },
//                { AmountUnit.Peck, "pk" },
//                { AmountUnit.Case, "case" },
//                { AmountUnit.GrossScore, "grs" },
//                { AmountUnit.Quire, "quire" },
//                { AmountUnit.Sheet, "sheet" },
//                { AmountUnit.BakerDozen, "baker's dozen" },
//                { AmountUnit.Cartons, "cartons" },
//                { AmountUnit.Fortnight, "fortnight" },
//                { AmountUnit.Bale, "bale" },
//                { AmountUnit.MetricTon, "t" },
//                { AmountUnit.Hundredweight, "cwt" },
//                { AmountUnit.Bushel, "bu" },
//                { AmountUnit.Octad, "octad" },
//                { AmountUnit.GrossHundredweight, "grcwt" }
//            }
//        }
//    };
//}